name: azureinfluxpanda
dependencies:
  - numpy=1.12.1
  - pandas=0.22.0
  - python=3.6.5
  - pytest=3.7.3
  - plotly=3.1.1
  - jupyter=1.0.0
  - pip:
    - influxdb==5.0.0
    - azure-datalake-store==0.0.31
    - azure-mgmt-resource==2.0.0
    - azure-mgmt-datalake-store==0.5.0